name: Build and Push Image

on:
  push:
  workflow_dispatch:

env:
  # Uses docker.io for Docker Hub if REGISTRY is empty
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Check disk space
        run: |
          du -hs .
          df -h .

      # Checkout the repository
      # Repo: https://github.com/marketplace/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      # Repo: https://github.com/marketplace/actions/docker-setup-buildx
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.10.0

      # Login against a Docker registry except on PR
      # Repo: https://github.com/marketplace/actions/docker-login
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Pull an existing image
      - name: Pull existing image
        run: |
          docker pull ghcr.io/${{ github.repository }}:main || true

      # Setup Docker buildx

      # Extract metadata (tags, labels) for Docker
      # Repo: https://github.com/marketplace/actions/docker-metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=short,prefix=,suffix=
            type=sha,format=long,prefix=,suffix=
            type=ref,event=branch,prefix=,suffix=

      - name: Disply metadata
        run: |
          cat ${{steps.meta.outputs.bake-file }}

      # Archive metadata for use in other steps
      # Repo: https://github.com/marketplace/actions/upload-a-build-artifact
      - name: Archive metadata
        uses: actions/upload-artifact@v4.6.1
        with:
          name: metadata.json
          path: ${{steps.meta.outputs.bake-file }}

      # Build and push Docker images with Buildx (don't push on PR)
      # Repo: https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}